# Generated by Django 3.1.7 on 2021-03-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210303_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='company',
            name='exchange',
        ),
        migrations.RemoveField(
            model_name='company',
            name='industry',
        ),
        migrations.AddField(
            model_name='company',
            name='country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='index',
            field=models.CharField(default='term', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='market_cap',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
